"""
ue_codegen.py
-------------
Excel 스키마로부터 UE5 C++ DataTable Row Struct 헤더를 자동 생성한다.

main.py 파이프라인에서 호출되며, 독립 실행도 가능하다.

사용법 (독립 실행):
  python ue_codegen.py                          # config.yaml 기본 설정 사용
  python ue_codegen.py --output path/to/out.h   # 출력 경로 오버라이드
"""

from __future__ import annotations

from pathlib import Path

from excel_parser import ExcelData, FieldDef


# ---------------------------------------------------------------------------
# 타입 매핑
# ---------------------------------------------------------------------------

_SCALAR_TYPE_MAP: dict[str, str] = {
    "int32":  "int32",
    "int64":  "int64",
    "uint32": "uint32",
    "uint64": "uint64",
    "float":  "float",
    "double": "double",
    "bool":   "bool",
    "string": "FString",
}

_DEFAULT_VALUE: dict[str, str] = {
    "int32":  "0",
    "int64":  "0",
    "uint32": "0",
    "uint64": "0",
    "float":  "0.f",
    "double": "0.0",
    "bool":   "false",
}

# 메시지명 → Row Struct 이름 (F 접두어 제외)
# ImportDataTables.py의 TABLE_STRUCT_MAP과 일치해야 한다.
STRUCT_NAME_MAP: dict[str, str] = {
    "PawnData":        "PawnDataRow",
    "MonsterData":     "MonsterDataRow",
    "CardData":        "CardDataRow",
    "CardEffectData":  "CardEffectRow",
    "EquipmentData":   "EquipmentDataRow",
    "TileEntityData":  "TileEntityRow",
    "StagePresetData": "StagePresetRow",
    "StageRewardData": "StageRewardRow",
    "ShopData":        "ShopDataRow",
    "PawnGrowthData":  "PawnGrowthRow",
    "NamePresetData":  "NamePresetRow",
    "TextData":        "TextRow",
}

# camelCase → PascalCase 특수 변환 (대문자 약어 등)
_NAME_OVERRIDES: dict[str, str] = {
    "hp": "HP",
}


# ---------------------------------------------------------------------------
# 헬퍼
# ---------------------------------------------------------------------------

def _to_pascal(name: str, field_type: str) -> str:
    """camelCase 필드명을 UE5 PascalCase UPROPERTY명으로 변환한다."""
    if name in _NAME_OVERRIDES:
        result = _NAME_OVERRIDES[name]
    else:
        result = name[0].upper() + name[1:]

    # UE5 bool 컨벤션: b 접두어
    if field_type == "bool" and not result.startswith("b"):
        result = "b" + result

    return result


def _field_to_cpp(fd: FieldDef) -> tuple[str, str | None]:
    """
    FieldDef → (C++ 타입 문자열, 기본값 or None).

    repeated 필드의 TArray 래핑은 호출부에서 처리한다.
    """
    ft = fd.field_type

    # enum:EnumName → EEnumName
    if ft.startswith("enum:"):
        enum_name = ft[5:]
        cpp = f"E{enum_name}"
        return cpp, f"E{enum_name}::None"

    # classref:ClassName → TSoftClassPtr<ClassName>
    if ft.startswith("classref:"):
        cls = ft[9:]
        return f"TSoftClassPtr<{cls}>", None

    # asset:ClassName → TSoftObjectPtr<ClassName>
    if ft.startswith("asset:"):
        cls = ft[6:]
        return f"TSoftObjectPtr<{cls}>", None

    # 스칼라 타입
    if ft in _SCALAR_TYPE_MAP:
        return _SCALAR_TYPE_MAP[ft], _DEFAULT_VALUE.get(ft)

    # 알 수 없는 타입 → FString fallback
    return "FString", None


def _collect_forward_decls(
    schema: dict[str, list[FieldDef]],
    struct_map: dict[str, str],
) -> list[str]:
    """classref/asset 타입에서 참조하는 클래스의 전방선언을 수집한다."""
    classes: set[str] = set()
    for msg_name, fields in schema.items():
        if msg_name not in struct_map:
            continue
        for fd in fields:
            if fd.field_type.startswith("classref:"):
                classes.add(fd.field_type[9:])
            elif fd.field_type.startswith("asset:"):
                classes.add(fd.field_type[6:])

    return [f"class {cls};" for cls in sorted(classes)]


# ---------------------------------------------------------------------------
# 공개 API
# ---------------------------------------------------------------------------

def generate_row_header(
    excel_data: ExcelData,
    output_path: Path,
    struct_map: dict[str, str] | None = None,
) -> str:
    """
    ExcelData 스키마로부터 CardGameRowTypes.h를 생성한다.

    Args:
        excel_data:  파싱된 Excel 데이터
        output_path: 생성할 헤더 파일 경로
        struct_map:  {MessageName: StructName} 매핑 (None이면 기본값 사용)

    Returns:
        생성된 파일 경로 문자열
    """
    if struct_map is None:
        struct_map = STRUCT_NAME_MAP

    forward_decls = _collect_forward_decls(excel_data.schema, struct_map)

    lines: list[str] = [
        "// Auto-generated by CardGame Table Tool",
        "// DO NOT EDIT MANUALLY",
        "",
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        '#include "Engine/DataTable.h"',
        '#include "CardGameTypes.h"',
        '#include "CardGameRowTypes.generated.h"',
        "",
    ]

    if forward_decls:
        lines.extend(forward_decls)
        lines.append("")

    idx = 0
    for msg_name, fields in excel_data.schema.items():
        struct_name = struct_map.get(msg_name)
        if not struct_name:
            continue
        idx += 1

        separator = "\u2500" * max(1, 55 - len(msg_name) - len(str(idx)))
        lines.append(f"// \u2500\u2500 {idx}. {msg_name} {separator}")
        lines.append("USTRUCT(BlueprintType)")
        lines.append(f"struct F{struct_name} : public FTableRowBase")
        lines.append("{")
        lines.append("\tGENERATED_BODY()")
        lines.append("")

        for fd in fields:
            # {X}IdAlias 헬퍼 필드는 C++ 구조체에서 제외
            # (data_serializer에서 alias 해석용으로만 사용)
            if fd.field_name != "idAlias" and fd.field_name.endswith("IdAlias"):
                continue

            cpp_type, default_val = _field_to_cpp(fd)

            if fd.rule == "repeated":
                cpp_type = f"TArray<{cpp_type}>"
                default_val = None

            prop_name = _to_pascal(fd.field_name, fd.field_type)
            line = f"\tUPROPERTY(EditAnywhere, BlueprintReadWrite) {cpp_type} {prop_name}"
            if default_val:
                line += f" = {default_val}"
            line += ";"
            lines.append(line)

        lines.append("};")
        lines.append("")

    content = "\n".join(lines)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return str(output_path)


# ---------------------------------------------------------------------------
# 독립 실행
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse
    import sys

    import yaml

    TOOL_DIR = Path(__file__).parent.resolve()

    parser = argparse.ArgumentParser(description="Excel 스키마 → UE5 Row Struct 헤더 생성")
    parser.add_argument("--config", default=str(TOOL_DIR / "config.yaml"))
    parser.add_argument("--output", help="출력 헤더 경로 (config.yaml 오버라이드)")
    args = parser.parse_args()

    tool_str = str(TOOL_DIR)
    if tool_str not in sys.path:
        sys.path.insert(0, tool_str)

    with open(args.config, encoding="utf-8") as f:
        config = yaml.safe_load(f)

    from excel_parser import parse_excel_multi

    schema_dir = (TOOL_DIR / config["schema_dir"]).resolve()
    data_dir = (TOOL_DIR / config["data_dir"]).resolve()
    excel_data = parse_excel_multi(schema_dir, data_dir)

    out_path = Path(args.output) if args.output else (
        TOOL_DIR / config.get("ue_header_path", "../Source/Dev_GNC/CardGame/Data/CardGameRowTypes.h")
    ).resolve()

    result = generate_row_header(excel_data, out_path)
    print(f"[OK] 생성 완료: {result}")


if __name__ == "__main__":
    main()
